version: '3.8'

services:
  web:
    build: .
    command: sh -c "flask --app flask_app/app.py db migrate &&
      flask --app flask_app/app.py db upgrade && python run.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/project/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - tt_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${PG_PORT}:5432
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.admin"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "5050:80"

volumes:
  tt_data: