"""empty message

Revision ID: b50c1be85821
Revises: 
Create Date: 2023-03-28 21:44:07.543125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b50c1be85821"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=32), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("photo_url", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.String(length=140), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        sa.UniqueConstraint("user_name"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("users")
    # ### end Alembic commands ###
